name: release-please

on:
  push:
    branches:
      - master

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: Release-please check
        id: release
        uses: google-github-actions/release-please-action@v3 
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: node
          changelog-path: CHANGELOG.md

      - name: Checkout codebase
        uses: actions/checkout@v2
        if: ${{ steps.release.outputs.release_created }}

      - name: Setup NodeJS 16
        uses: actions/setup-node@v3
        if: ${{ steps.release.outputs.release_created }}
        with:
          node-version: 16
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        if: ${{ steps.release.outputs.release_created }}
        run: yarn install --pure-lockfile

      - name: Build plugin
        if: ${{ steps.release.outputs.release_created }}
        run: yarn run build

      - name: Sign plugin
        if: ${{ steps.release.outputs.release_created }}
        env:
          GRAFANA_API_KEY: ${{ secrets.GRAFANA_API_KEY }}
        run: yarn sign

      - name: Package plugin
        if: ${{ steps.release.outputs.release_created }}
        run: |
          mkdir build
          mv dist/ camptocamp-prometheus-alertmanager-datasource
          zip -r build/camptocamp-prometheus-alertmanager-datasource-${{ steps.release.outputs.tag_name }}.zip ./camptocamp-prometheus-alertmanager-datasource
          md5sum build/camptocamp-prometheus-alertmanager-datasource-${{ steps.release.outputs.tag_name }}.zip > build/camptocamp-prometheus-alertmanager-datasource-${{ steps.release.outputs.tag_name }}.zip.md5
     
      - name: Upload Assets to Release
        uses: csexton/release-asset-action@v2
        with:
          pattern: "build/*"
          github-token: ${{ secrets.GITHUB_TOKEN }}
          release-url: ${{ steps.release.outputs.upload_url }} 
